"""Per-agent standards file generator — `--init-agent-standards`.

For each target host (codex, claude-code, cursor, copilot, windsurf, generic),
emit a standing-instructions file that tells the agent how to behave when
asked to fix security findings in this repo. Additive to repo-specific rules
in AGENTS.md / CLAUDE.md.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

# Map target → (filename, friendly_label)
_TARGETS: dict[str, tuple[str, str]] = {
    "codex":         ("AGENTS.md",                                "Codex (AGENTS.md)"),
    "claude-code":   ("CLAUDE.md",                                "Claude Code (CLAUDE.md)"),
    "cursor":        (".cursor/rules/security.mdc",               "Cursor (.cursor/rules/security.mdc)"),
    "copilot":       (".github/copilot-instructions.md",          "GitHub Copilot (.github/copilot-instructions.md)"),
    "windsurf":      (".windsurf/rules/security.md",              "Windsurf (.windsurf/rules/security.md)"),
    "generic":       ("AI-SECURITY-STANDARDS.md",                 "Generic agent (AI-SECURITY-STANDARDS.md)"),
}


_BODY = """\
# AI agent security standards (generated by secure-code-agent)

This file is **appended** to the repo's existing AI-agent instructions.
It encodes the bounded-remediation rules `secure-code-agent` enforces. If
this file conflicts with the repo's own `AGENTS.md` / `CLAUDE.md`,
**repo-specific rules win**.

## When you are asked to fix a security finding

1. **Read `secure-code-remediation-prompt.md` first if it exists.** It
   is the canonical, finding-scoped task brief.
2. **If no prompt exists**, run `secure-code-agent --prompt-output
   secure-code-remediation-prompt.md` first, then read it.
3. Follow the prompt's hard constraints verbatim.

## Standing rules (apply to ALL security-related work in this repo)

- **Do not change cryptographic algorithms, key derivation, IV/nonce
  handling, padding modes, or random sources** unless a finding
  explicitly names them as the defect.
- **Do not change authentication flows, session handling, token
  lifetime, cookie attributes, or authorization gates** unless a
  finding explicitly names them.
- **Do not weaken input validation, output encoding, sanitization,
  bounds checks, regex strictness, or rate limits** to make existing
  tests pass.
- **Do not disable, delete, or skip security tests.** Do not remove
  `@_limiter.limit`, `@require_auth`, `@require_csrf`, or similar
  decorators.
- **Do not silence linter warnings** via `# nosec`, `# noqa`,
  `# type: ignore`, `eslint-disable`, `sonar-disable`, or
  equivalent.
- **Do not introduce new third-party dependencies.** Prefer stdlib
  or already-vendored libraries. If a new dependency is necessary,
  stop and ask the operator first.
- **Preserve behavior.** Same inputs must produce the same outputs
  unless a finding explicitly proves the current behavior is
  unsafe.
- **Add a focused test** that exercises the specific security
  boundary you fixed. The test must FAIL on the pre-fix code and
  PASS on the post-fix code.
- **Keep patches small.** If you find yourself rewriting a function
  rather than patching it, stop and report the structural issue
  to the operator.

## Standards anchors

Findings carry: CWE id, OWASP Top 10 bucket, OWASP ASVS section,
NIST SSDF practice. Read the standards entries before editing —
they are the authoritative description of the weakness.

- CWE: https://cwe.mitre.org/data/definitions/<num>.html
- OWASP Top 10: https://owasp.org/Top10/2021/
- OWASP ASVS: https://github.com/OWASP/ASVS
- NIST SSDF: https://csrc.nist.gov/pubs/sp/800/218/final

## False positives

If a finding is a false positive, do NOT silently apply a fix.
Add a suppression entry to `.scignore.yaml` with:

  - `rule_id` (or `*` scoped to `file`/`paths`)
  - `reason` (required, non-empty)
  - `expires` (required, ISO date, ≤ 365 days from today)

The operator will review the suppression in PR.
"""


def render() -> str:
    """Return the generated body. Operators may append additional
    repo-specific rules to the emitted file after the first run."""
    return _BODY


def write_for_target(target: str, output_dir: Path) -> Path:
    if target not in _TARGETS:
        raise ValueError(
            f"Unknown target {target!r}. Known: {', '.join(sorted(_TARGETS))}."
        )
    rel_path, _ = _TARGETS[target]
    out = output_dir / rel_path
    out.parent.mkdir(parents=True, exist_ok=True)
    body = render()

    # If the target file exists, append below a fenced section so the
    # operator's existing content is preserved.
    if out.exists():
        existing = out.read_text(encoding="utf-8")
        marker   = "<!-- secure-code-agent:standards -->"
        if marker in existing:
            # Already initialized; refresh between markers.
            before, _, rest    = existing.partition(marker)
            _, _, after_close  = rest.partition("<!-- /secure-code-agent:standards -->")
            new = f"{before}{marker}\n{body}\n<!-- /secure-code-agent:standards -->{after_close}"
        else:
            new = (
                f"{existing.rstrip()}\n\n"
                f"{marker}\n{body}\n<!-- /secure-code-agent:standards -->\n"
            )
    else:
        new = (
            "<!-- secure-code-agent:standards -->\n"
            f"{body}\n"
            "<!-- /secure-code-agent:standards -->\n"
        )

    out.write_text(new, encoding="utf-8")
    return out


def write_for_targets(targets: Iterable[str], output_dir: Path) -> list[Path]:
    return [write_for_target(t, output_dir) for t in targets]


def known_targets() -> list[str]:
    return sorted(_TARGETS.keys())
